---
# Handlers fÃ¼r desktop Role

- name: Restart bluetooth
  ansible.builtin.systemd:
    name: bluetooth
    state: restarted

- name: Restart cups
  ansible.builtin.systemd:
    name: cups
    state: restarted

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
