---
all:
  children:
    workstations:
      hosts:
        schwerer:
          ansible_host: localhost
          ansible_connection: local

    vms:
      hosts:
        cachyos:
          ansible_host: 192.168.122.237ich w  # Anpassen falls andere IP
          ansible_user: mauschel
          ansible_become: true
          ansible_become_method: sudo

    # Für später: weitere Hosts
    # laptops:
    #   hosts:
    #     FlotteBunte:
    #       ansible_host: 192.168.1.101
