---
# Defaults für gaming Role

steam_enabled: true
emulators_enabled: true
wine_enabled: true

# Steam Firewall Ports
steam_tcp_ports:
  - 27015
  - 27036
  - 27037
steam_udp_ports:
  - 27015
  - 27031
  - 27036
  - 4380

# Controller
xbox_controller: true
playstation_controller: true
nintendo_controller: true

# Kernel Parameters für Gaming Performance
gaming_kernel_params:
  - "mitigations=off"
  - "nowatchdog"
  - "nmi_watchdog=0"

# Memory Lock Limits
gaming_memlock_limit: "unlimited"
