---
# Syncthing Setup

- name: Install Syncthing
  ansible.builtin.package:
    name: syncthing
    state: present

- name: Enable Syncthing user service
  become: true
  become_user: "{{ syncthing_user }}"
  ansible.builtin.systemd:
    name: syncthing
    scope: user
    enabled: true
    state: started
  ignore_errors: true

- name: Open Syncthing ports in firewall (UFW)
  when: ansible_os_family == "Debian"
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "8384"   # Web UI
    - "22000"  # Sync
  ignore_errors: true

- name: Open Syncthing ports in firewall (firewalld)
  when: ansible_distribution == "Fedora"
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "8384"
    - "22000"
  ignore_errors: true
