---
# Handlers f√ºr base Role

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Reload firewall
  ansible.builtin.systemd:
    name: "{{ firewall_service }}"
    state: reloaded
