---
# Defaults f√ºr desktop Role

# Display Manager
display_manager: "gdm"  # gdm, sddm, lightdm

# Audio
audio_system: "pipewire"  # pipewire oder pulseaudio

# Bluetooth
bluetooth_enabled: true

# Printing
printing_enabled: true

# Docker
docker_enabled: true

# Libvirt/QEMU
libvirt_enabled: true

# Syncthing
syncthing_enabled: true
syncthing_user: "{{ main_user }}"
syncthing_data_dir: "/home/{{ main_user }}/Documents"

# Desktop-Pakete
desktop_packages_common:
  - firefox
  - vlc
  - terminator
  - blender
  - inkscape
  - krita
  - libreoffice
  - copyq
  - conky

desktop_packages_arch:
  - firefox
  - vlc
  - terminator
  - blender
  - inkscape
  - krita
  - libreoffice-fresh
  - copyq
  - conky
  - brave-bin  # AUR
  - thunderbird
  - mplayer
  - solaar
  - direnv

desktop_packages_debian:
  - firefox
  - vlc
  - terminator
  - blender
  - inkscape
  - krita
  - libreoffice
  - copyq
  - conky-all
  - thunderbird
  - mplayer
  - solaar
  - direnv

desktop_packages_fedora:
  - firefox
  - vlc
  - terminator
  - blender
  - inkscape
  - krita
  - libreoffice
  - copyq
  - conky
  - thunderbird
  - mplayer
  - solaar
  - direnv
