---
# Handlers f√ºr nvidia Role

- name: Update GRUB
  ansible.builtin.command:
    cmd: update-grub
  when: ansible_os_family == "Debian"

- name: Rebuild initramfs
  ansible.builtin.command:
    cmd: mkinitcpio -P
  when: ansible_distribution == "Archlinux"
